
// import std.unittest.*
// import std.unittest.testmacro.*
// import mysql.connection.*
// import std.collection.*

// @Test
// public class OceanBaseTest {

//     @TestCase
//     public func case1(): Unit {
//         var attr = HashMap<String, String>()
//         attr.add(Params.Username, "yesokim")
//         attr.add(Params.Password, "^ynAW@7W5Fdxi6f")
//         attr.add(Params.Host, "obmtm94oeja8d1h0-mi.cn-hangzhou.oceanbase.aliyuncs.com")
//         attr.add(Params.Port, "3306")
//         attr.add(Params.SSLMode, "disabled")
//         var conn = MySqlConnectionFactory.createAuthedConnection(attr)
//         conn.close()
//     }

//     @TestCase
//     public func case2(): Unit {
//         var attr = HashMap<String, String>()
//         attr.add(Params.Username, "yesokim")
//         attr.add(Params.Password, "^ynAW@7W5Fdxi6f")
//         attr.add(Params.Host, "obmtm94oeja8d1h0-mi.cn-hangzhou.oceanbase.aliyuncs.com")
//         attr.add(Params.Port, "3306")
//         var conn = MySqlConnectionFactory.createAuthedConnection(attr)
//         conn.close()
//     }

// }