[package]
  cjc-version = "0.60.5"
  compile-option = "-O2"
  description = ""
  link-option = ""
  name = "mysql"
  output-type = "static"
  src-dir = ""
  target-dir = ""
  version = "0.8.0"
  [package.package-configuration]


# [target.x86_64-w64-mingw32.bin-dependencies]
#   path-option = [ "C:/Users/30247/Desktop/Cangjie/Cangjie-0.60.5/cangjie-stdx-windows-x64-0.60.5.1/windows_x86_64_llvm/dynamic/stdx" ]
[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = [ "${CANGJIE_STDX}" ]
[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = [ "${CANGJIE_STDX}" ]
[target.aarch64-darwin.bin-dependencies]
  path-option = [ "${CANGJIE_STDX}" ]