[package]
  cjc-version = "0.56.4"
  compile-option = "--incremental-compile --diagnostic-format=noColor"
  description = ""
  link-option = ""
  name = "mysqlclient4cj"
  output-type = "static"
  src-dir = ""
  target-dir = ""
  version = "0.6.0"
[package.package-configuration]
