protected package mysql.test.connection

import std.unittest.*
import std.unittest.testmacro.*
import mysql.connection.*
import std.collection.*

// @Test
// public class TidbTest {
    
//     @TestCase
//     public func case1() {
//         var attr = HashMap<String, String>()
//         attr.add(Params.Username, "3VaBbhPVncyrhn6.root")
//         attr.add(Params.Password, "vLCfT9KIHkTonNft")
//         attr.add(Params.Host, "gateway01.ap-northeast-1.prod.aws.tidbcloud.com")
//         attr.add(Params.Port, "4000")
//         //attr.add(Params.SSLMode, "disabled")
//         var conn = MySqlConnectionFactory.createAuthedConnection(attr)
//         conn.close()
//     }

// }